# Generated by Django 2.2 on 2020-08-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pol',
            options={'verbose_name': 'Оопрос', 'verbose_name_plural': 'Оопросы'},
        ),
        migrations.AlterField(
            model_name='pol',
            name='question',
            field=models.TextField(max_length=2000, verbose_name='Оопрос'),
        ),
    ]
