# Generated by Django 2.2 on 2020-08-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200829_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pol',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
